version: 2.1
jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Test:tsc
          command: npx tsc --noEmit
      - run:
          name: Test:lint
          command: npm run lint
      - run:
          name: Test:unit
          command: npx jest /src.*__spec__/ --coverage -i -ci
      - run:
          name: Test:int
          command: npx jest /src.*__test__/ --coverage -i -ci
